-- BAGAY event store (PostgreSQL 16)
-- Source of truth: an append-only, hash-chained event log.
-- Everything else (projections, dashboards, queues) is rebuilt from this schema.
--
-- Hashes are computed by the Command API (see design doc, "Hash chain"):
--   event_hash = SHA-256( prev_hash || stream_prev_hash || int8be(global_position) || JCS(envelope) )
-- The database does not recompute hashes; it enforces LINKAGE (positions, prev pointers,
-- stream versions) and forbids UPDATE / DELETE / TRUNCATE. The verifier checks the hashes.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS es;

-- ---------------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------------
CREATE TYPE es.trust_level AS ENUM (
  'PUBLIC_CLAIM',      -- anonymous resident report via QR page
  'OFFICER_ATTESTED',  -- recorded by an authenticated barangay officer or worker
  'APPROVED'           -- attested and approved by the Punong Barangay (two-person rule)
);

CREATE TYPE es.event_source AS ENUM ('WEB', 'PWA_OFFLINE', 'QR_PUBLIC', 'SYSTEM', 'IMPORT');

-- ---------------------------------------------------------------------------
-- The log
-- ---------------------------------------------------------------------------
CREATE TABLE es.events (
  global_position   BIGINT       PRIMARY KEY CHECK (global_position >= 1),
  event_id          UUID         NOT NULL UNIQUE,          -- UUIDv7, generated by the client (idempotency key)
  stream_id         TEXT         NOT NULL,                 -- e.g. 'asset:BGY-1380600000-SL-00012'
  stream_version    INTEGER      NOT NULL CHECK (stream_version >= 1),
  event_type        TEXT         NOT NULL,                 -- e.g. 'DamageRecorded'
  schema_version    SMALLINT     NOT NULL DEFAULT 1,
  occurred_at       TIMESTAMPTZ  NOT NULL,                 -- when it happened in the field (client clock)
  recorded_at       TIMESTAMPTZ  NOT NULL,                 -- when the server accepted it (server clock)
  actor_id          TEXT         NOT NULL,                 -- 'user:<uuid>' or 'public:<session-hash>' or 'system'
  actor_role        TEXT         NOT NULL,
  trust_level       es.trust_level  NOT NULL,
  source            es.event_source NOT NULL,
  correlation_id    UUID,
  causation_id      UUID,
  payload           JSONB        NOT NULL,                 -- never contains raw personal data (see vault schema)
  attachments       TEXT[]       NOT NULL DEFAULT '{}',    -- SHA-256 hex digests of photos in the blob store
  prev_hash         BYTEA        NOT NULL CHECK (octet_length(prev_hash) = 32),
  stream_prev_hash  BYTEA        NOT NULL CHECK (octet_length(stream_prev_hash) = 32),
  event_hash        BYTEA        NOT NULL UNIQUE CHECK (octet_length(event_hash) = 32),
  UNIQUE (stream_id, stream_version)
);

CREATE INDEX events_stream_idx ON es.events (stream_id, stream_version);
CREATE INDEX events_type_idx   ON es.events (event_type);
CREATE INDEX events_time_idx   ON es.events (occurred_at);

-- Chain head (exactly one row) and per-stream heads
CREATE TABLE es.chain_head (
  singleton   BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
  position    BIGINT  NOT NULL,
  head_hash   BYTEA   NOT NULL
);
INSERT INTO es.chain_head VALUES (TRUE, 0, decode(repeat('00', 32), 'hex'));

CREATE TABLE es.stream_heads (
  stream_id   TEXT    PRIMARY KEY,
  version     INTEGER NOT NULL,
  head_hash   BYTEA   NOT NULL
);

-- ---------------------------------------------------------------------------
-- Linkage enforcement
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION es.enforce_linkage() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = es, pg_temp AS $$
DECLARE
  h   es.chain_head%ROWTYPE;
  sh  es.stream_heads%ROWTYPE;
  zero BYTEA := decode(repeat('00', 32), 'hex');
BEGIN
  -- Serialise all writers on the chain head.
  SELECT * INTO h FROM es.chain_head WHERE singleton FOR UPDATE;

  IF NEW.global_position <> h.position + 1 THEN
    RAISE EXCEPTION 'BAGAY-CHAIN: expected global_position %, got %', h.position + 1, NEW.global_position
      USING ERRCODE = 'BGC01';
  END IF;
  IF NEW.prev_hash <> h.head_hash THEN
    RAISE EXCEPTION 'BAGAY-CHAIN: prev_hash does not match chain head at position %', h.position
      USING ERRCODE = 'BGC01';
  END IF;

  SELECT * INTO sh FROM es.stream_heads WHERE stream_id = NEW.stream_id FOR UPDATE;
  IF NOT FOUND THEN
    IF NEW.stream_version <> 1 OR NEW.stream_prev_hash <> zero THEN
      RAISE EXCEPTION 'BAGAY-STREAM: new stream % must start at version 1 with zero stream_prev_hash', NEW.stream_id
        USING ERRCODE = 'BGS01';
    END IF;
    INSERT INTO es.stream_heads VALUES (NEW.stream_id, 1, NEW.event_hash);
  ELSE
    IF NEW.stream_version <> sh.version + 1 THEN
      -- optimistic concurrency conflict: the client decided on stale state
      RAISE EXCEPTION 'BAGAY-CONFLICT: stream % is at version %, command expected %',
        NEW.stream_id, sh.version, NEW.stream_version - 1
        USING ERRCODE = 'BGV01';
    END IF;
    IF NEW.stream_prev_hash <> sh.head_hash THEN
      RAISE EXCEPTION 'BAGAY-STREAM: stream_prev_hash mismatch on %', NEW.stream_id
        USING ERRCODE = 'BGS01';
    END IF;
    UPDATE es.stream_heads SET version = NEW.stream_version, head_hash = NEW.event_hash
     WHERE stream_id = NEW.stream_id;
  END IF;

  UPDATE es.chain_head SET position = NEW.global_position, head_hash = NEW.event_hash WHERE singleton;
  RETURN NEW;
END $$;

CREATE TRIGGER events_linkage BEFORE INSERT ON es.events
  FOR EACH ROW EXECUTE FUNCTION es.enforce_linkage();

CREATE OR REPLACE FUNCTION es.forbid_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'BAGAY-IMMUTABLE: % on es.events is not allowed; append a correcting event instead', TG_OP
    USING ERRCODE = 'BGI01';
END $$;

CREATE TRIGGER events_no_update   BEFORE UPDATE ON es.events FOR EACH ROW EXECUTE FUNCTION es.forbid_mutation();
CREATE TRIGGER events_no_delete   BEFORE DELETE ON es.events FOR EACH ROW EXECUTE FUNCTION es.forbid_mutation();
CREATE TRIGGER events_no_truncate BEFORE TRUNCATE ON es.events FOR EACH STATEMENT EXECUTE FUNCTION es.forbid_mutation();

-- Wake the relay without polling delay.
CREATE OR REPLACE FUNCTION es.notify_append() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_notify('bagay_events', NEW.global_position::text);
  RETURN NULL;
END $$;

CREATE TRIGGER events_notify AFTER INSERT ON es.events
  FOR EACH ROW EXECUTE FUNCTION es.notify_append();

-- ---------------------------------------------------------------------------
-- Checkpoints (published to external witnesses)
-- ---------------------------------------------------------------------------
CREATE TABLE es.checkpoints (
  checkpoint_no  BIGSERIAL    PRIMARY KEY,
  position       BIGINT       NOT NULL UNIQUE,
  head_hash      BYTEA        NOT NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  reason         TEXT         NOT NULL CHECK (reason IN ('SCHEDULED', 'TURNOVER', 'MANUAL', 'HAZARD')),
  signature      BYTEA,                         -- Ed25519 over the canonical checkpoint statement
  key_id         TEXT,
  published_to   JSONB        NOT NULL DEFAULT '[]'   -- [{channel, reference, at}]
);

-- Relay bookmark (which positions were confirmed by the broker)
CREATE TABLE es.relay_state (
  relay_name     TEXT PRIMARY KEY,
  last_position  BIGINT NOT NULL DEFAULT 0,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO es.relay_state (relay_name) VALUES ('rabbitmq');

-- ---------------------------------------------------------------------------
-- Least privilege
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bagay_writer') THEN CREATE ROLE bagay_writer; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bagay_reader') THEN CREATE ROLE bagay_reader; END IF;
END $$;

REVOKE ALL ON ALL TABLES IN SCHEMA es FROM PUBLIC;
GRANT USAGE ON SCHEMA es TO bagay_writer, bagay_reader;
GRANT SELECT, INSERT ON es.events TO bagay_writer;
GRANT SELECT ON es.chain_head, es.stream_heads TO bagay_writer;  -- heads change only through the SECURITY DEFINER trigger
GRANT SELECT, INSERT, UPDATE ON es.checkpoints, es.relay_state TO bagay_writer;
GRANT USAGE ON SEQUENCE es.checkpoints_checkpoint_no_seq TO bagay_writer;
GRANT SELECT ON ALL TABLES IN SCHEMA es TO bagay_reader;
